[tool.poetry]
name = "solar panel sim"
version = "0.1.0"
description = ""
authors = ["Nathan Kester"]


[tool.poetry.dependencies]
python = "^3.11"
pytest = "^8.3.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
